export const wallets = [
  {
    id: 1,
    name: "Flexidy",
    initial_balance: 38424,
    current_balance: 4354,
    currency: "USD",
  },
  {
    id: 2,
    name: "Rank",
    initial_balance: 46120,
    current_balance: 20599,
    currency: "BHD",
  },
  {
    id: 3,
    name: "Subin",
    initial_balance: 44689,
    current_balance: 2358,
    currency: "EUR",
  },
  {
    id: 4,
    name: "Voyatouch",
    initial_balance: 28985,
    current_balance: 4941,
    currency: "AED",
  },
]

export const transactions = [
  {
    id: 1,
    wallet_id: 1,
    category_id: 9,
    date: "7/5/2023",
    note: "Intuitive dedicated help-desk",
    amount: 28,
    type: "income",
    label_id: 6,
  },
  {
    id: 2,
    wallet_id: 3,
    category_id: 8,
    date: "8/30/2022",
    note: "Sharable asymmetric website",
    amount: 17,
    type: "income",
    label_id: 4,
  },
  {
    id: 3,
    wallet_id: 4,
    category_id: 10,
    date: "10/8/2022",
    note: "Ameliorated context-sensitive throughput",
    amount: 82,
    type: "income",
    label_id: 9,
  },
  {
    id: 4,
    wallet_id: 3,
    category_id: 5,
    date: "8/17/2022",
    note: "Reduced 4th generation archive",
    amount: 5,
    type: "expense",
    label_id: 10,
  },
  {
    id: 5,
    wallet_id: 3,
    category_id: 2,
    date: "1/17/2023",
    note: "Versatile background encoding",
    amount: 90,
    type: "expense",
    label_id: 5,
  },
  {
    id: 6,
    wallet_id: 3,
    category_id: 5,
    date: "7/31/2023",
    note: "Re-contextualized eco-centric conglomeration",
    amount: 73,
    type: "expense",
    label_id: 5,
  },
  {
    id: 7,
    wallet_id: 1,
    category_id: 9,
    date: "4/25/2023",
    note: "Multi-lateral methodical definition",
    amount: 64,
    type: "expense",
    label_id: 1,
  },
  {
    id: 8,
    wallet_id: 2,
    category_id: 1,
    date: "10/11/2022",
    note: "Sharable neutral project",
    amount: 69,
    type: "income",
    label_id: 7,
  },
  {
    id: 9,
    wallet_id: 2,
    category_id: 2,
    date: "7/12/2023",
    note: "Right-sized radical monitoring",
    amount: 85,
    type: "expense",
    label_id: 4,
  },
  {
    id: 10,
    wallet_id: 4,
    category_id: 9,
    date: "2/18/2023",
    note: "Compatible motivating definition",
    amount: 93,
    type: "expense",
    label_id: 6,
  },
  {
    id: 11,
    wallet_id: 2,
    category_id: 8,
    date: "3/10/2023",
    note: "Centralized zero tolerance algorithm",
    amount: 87,
    type: "expense",
    label_id: 6,
  },
  {
    id: 12,
    wallet_id: 2,
    category_id: 2,
    date: "8/2/2023",
    note: "Customer-focused homogeneous matrix",
    amount: 18,
    type: "expense",
    label_id: 4,
  },
  {
    id: 13,
    wallet_id: 4,
    category_id: 5,
    date: "8/15/2022",
    note: "Ergonomic system-worthy open architecture",
    amount: 67,
    type: "expense",
    label_id: 1,
  },
  {
    id: 14,
    wallet_id: 1,
    category_id: 10,
    date: "5/6/2023",
    note: "Integrated leading edge firmware",
    amount: 24,
    type: "income",
    label_id: 1,
  },
  {
    id: 15,
    wallet_id: 4,
    category_id: 10,
    date: "1/11/2023",
    note: "Open-architected systematic archive",
    amount: 39,
    type: "income",
    label_id: 9,
  },
  {
    id: 16,
    wallet_id: 3,
    category_id: 1,
    date: "7/7/2023",
    note: "Team-oriented 6th generation contingency",
    amount: 10,
    type: "expense",
    label_id: 10,
  },
  {
    id: 17,
    wallet_id: 3,
    category_id: 7,
    date: "8/17/2022",
    note: "Right-sized systemic Graphical User Interface",
    amount: 10,
    type: "income",
    label_id: 4,
  },
  {
    id: 18,
    wallet_id: 2,
    category_id: 4,
    date: "8/14/2023",
    note: "Compatible dedicated system engine",
    amount: 48,
    type: "expense",
    label_id: 7,
  },
  {
    id: 19,
    wallet_id: 3,
    category_id: 8,
    date: "2/14/2023",
    note: "Networked real-time model",
    amount: 21,
    type: "expense",
    label_id: 4,
  },
  {
    id: 20,
    wallet_id: 1,
    category_id: 2,
    date: "6/30/2023",
    note: "Persistent cohesive superstructure",
    amount: 22,
    type: "expense",
    label_id: 3,
  },
  {
    id: 21,
    wallet_id: 1,
    category_id: 1,
    date: "9/6/2023",
    note: "Switchable stable installation",
    amount: 8,
    type: "transfer",
    label_id: 2,
  },
  {
    id: 22,
    wallet_id: 3,
    category_id: 9,
    date: "8/16/2023",
    note: "Grass-roots clear-thinking concept",
    amount: 83,
    type: "income",
    label_id: 3,
  },
  {
    id: 23,
    wallet_id: 2,
    category_id: 9,
    date: "2/26/2023",
    note: "Customer-focused directional project",
    amount: 74,
    type: "expense",
    label_id: 3,
  },
  {
    id: 24,
    wallet_id: 4,
    category_id: 2,
    date: "9/7/2023",
    note: "Expanded local projection",
    amount: 92,
    type: "expense",
    label_id: 9,
  },
  {
    id: 25,
    wallet_id: 1,
    category_id: 1,
    date: "10/22/2022",
    note: "Synchronised mobile task-force",
    amount: 92,
    type: "expense",
    label_id: 2,
  },
  {
    id: 26,
    wallet_id: 3,
    category_id: 2,
    date: "5/5/2023",
    note: "Proactive client-server archive",
    amount: 56,
    type: "expense",
    label_id: 8,
  },
  {
    id: 27,
    wallet_id: 3,
    category_id: 1,
    date: "6/13/2023",
    note: "Total background process improvement",
    amount: 43,
    type: "expense",
    label_id: 3,
  },
  {
    id: 28,
    wallet_id: 2,
    category_id: 2,
    date: "2/22/2023",
    note: "Synergistic real-time secured line",
    amount: 35,
    type: "income",
    label_id: 1,
  },
  {
    id: 29,
    wallet_id: 4,
    category_id: 9,
    date: "11/18/2022",
    note: "Multi-lateral non-volatile installation",
    amount: 32,
    type: "income",
    label_id: 8,
  },
  {
    id: 30,
    wallet_id: 2,
    category_id: 5,
    date: "11/26/2022",
    note: "Integrated exuding extranet",
    amount: 67,
    type: "expense",
    label_id: 6,
  },
  {
    id: 31,
    wallet_id: 4,
    category_id: 10,
    date: "11/29/2022",
    note: "Object-based foreground secured line",
    amount: 15,
    type: "income",
    label_id: 2,
  },
  {
    id: 32,
    wallet_id: 4,
    category_id: 7,
    date: "9/30/2023",
    note: "Fundamental upward-trending superstructure",
    amount: 88,
    type: "income",
    label_id: 2,
  },
  {
    id: 33,
    wallet_id: 4,
    category_id: 10,
    date: "8/31/2023",
    note: "Configurable local customer loyalty",
    amount: 93,
    type: "income",
    label_id: 7,
  },
  {
    id: 34,
    wallet_id: 1,
    category_id: 5,
    date: "8/15/2022",
    note: "Organized bifurcated pricing structure",
    amount: 47,
    type: "income",
    label_id: 9,
  },
  {
    id: 35,
    wallet_id: 3,
    category_id: 10,
    date: "9/19/2023",
    note: "Organic systemic Graphic Interface",
    amount: 9,
    type: "income",
    label_id: 7,
  },
  {
    id: 36,
    wallet_id: 3,
    category_id: 6,
    date: "12/30/2022",
    note: "Total well-modulated structure",
    amount: 94,
    type: "expense",
    label_id: 1,
  },
  {
    id: 37,
    wallet_id: 4,
    category_id: 8,
    date: "12/15/2022",
    note: "Compatible heuristic intranet",
    amount: 28,
    type: "transfer",
    label_id: 5,
  },
  {
    id: 38,
    wallet_id: 1,
    category_id: 8,
    date: "7/8/2023",
    note: "Reverse-engineered neutral time-frame",
    amount: 17,
    type: "expense",
    label_id: 6,
  },
  {
    id: 39,
    wallet_id: 1,
    category_id: 5,
    date: "3/9/2023",
    note: "Cloned homogeneous structure",
    amount: 47,
    type: "expense",
    label_id: 3,
  },
  {
    id: 40,
    wallet_id: 1,
    category_id: 10,
    date: "2/25/2023",
    note: "Optimized optimal instruction set",
    amount: 88,
    type: "income",
    label_id: 8,
  },
  {
    id: 41,
    wallet_id: 3,
    category_id: 1,
    date: "11/21/2022",
    note: "Down-sized tangible definition",
    amount: 22,
    type: "expense",
    label_id: 3,
  },
  {
    id: 42,
    wallet_id: 3,
    category_id: 7,
    date: "8/7/2022",
    note: "Total object-oriented concept",
    amount: 76,
    type: "income",
    label_id: 10,
  },
  {
    id: 43,
    wallet_id: 2,
    category_id: 5,
    date: "12/17/2022",
    note: "Object-based local workforce",
    amount: 44,
    type: "expense",
    label_id: 2,
  },
  {
    id: 44,
    wallet_id: 2,
    category_id: 2,
    date: "3/26/2023",
    note: "Open-source 4th generation application",
    amount: 34,
    type: "expense",
    label_id: 8,
  },
  {
    id: 45,
    wallet_id: 1,
    category_id: 7,
    date: "8/6/2023",
    note: "Enterprise-wide 24 hour application",
    amount: 56,
    type: "income",
    label_id: 7,
  },
  {
    id: 46,
    wallet_id: 3,
    category_id: 7,
    date: "6/14/2023",
    note: "Expanded contextually-based hierarchy",
    amount: 57,
    type: "income",
    label_id: 8,
  },
  {
    id: 47,
    wallet_id: 1,
    category_id: 5,
    date: "9/18/2023",
    note: "Multi-layered eco-centric interface",
    amount: 18,
    type: "expense",
    label_id: 7,
  },
  {
    id: 48,
    wallet_id: 2,
    category_id: 7,
    date: "9/17/2022",
    note: "Persistent analyzing service-desk",
    amount: 17,
    type: "income",
    label_id: 1,
  },
  {
    id: 49,
    wallet_id: 2,
    category_id: 8,
    date: "7/22/2023",
    note: "Advanced interactive core",
    amount: 69,
    type: "expense",
    label_id: 10,
  },
  {
    id: 50,
    wallet_id: 3,
    category_id: 8,
    date: "2/19/2023",
    note: "Compatible foreground process improvement",
    amount: 84,
    type: "expense",
    label_id: 2,
  },
]
